rule:
  - label: exclude test
    type: forbidden_texts
    texts: [NGWORD]
    message: exclude対象テスト
    match:
      - pattern: path_contains
        keywords: [config/exclude_dirs]
        cond: or
