rule:
  - forbidden_texts:
      label: exclude test
      texts: [NGWORD]
      message: exclude対象テスト
      match:
        - pattern: path_contains
          keywords: [config/exclude_dirs]
          cond: or
